# 站点名称
site_name: Wubing Docs
# 版权
copyright: Copyright &copy 2023 wubing
# 开发地址
dev_addr: "127.0.0.1:11451"

# 额外参数
extra:
  generator: false
  analytics:
    provider: google
    property: G-1BJ0XH0RSM
  # 社区地址
  social:
    - icon: fontawesome/brands/github
#      link: https://github.com/MetaCubeX/mihomo
      link: https://github.com/yicheng2110/wubing-wiki

theme:
  name: material
  logo: assets/wx-log.jpg
  favicon: assets/wx-log.jpg
  features:
    - search.highlight
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - content.action.edit
    - content.code.copy
    - content.code.select
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3
      anchorlink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink

plugins:
  - search
  - awesome-pages

nav:
  - index.md
  - 技术栈:
      - techStack/index.md
#  - Web相关: index.md
  - 关于: about.md